-- =====================================================================
-- Tech Grid — Supabase schema
-- Run this in Supabase SQL editor in order: 01_schema.sql, 02_seed.sql,
-- 03_functions.sql, 04_cron.sql.
-- =====================================================================

-- Required extensions
create extension if not exists pgcrypto;
create extension if not exists pg_cron;
create extension if not exists pg_trgm;  -- for typeahead fuzzy matching

-- =====================================================================
-- Tables
-- =====================================================================

-- Products: the answer pool
create table if not exists products (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  slug          text not null unique,
  manufacturer  text,
  kind          text not null check (kind in ('software','hardware')),
  release_year  int,
  -- Free-form tag list used to satisfy categories. Examples:
  -- 'apple', 'open-source', 'mobile-app', 'console', 'has-touchscreen', 'ai'
  tags          text[] not null default '{}',
  -- Alternative names users may type (e.g. "PS5" for "PlayStation 5")
  aliases       text[] not null default '{}',
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

create index if not exists products_name_trgm on products using gin (name gin_trgm_ops);
create index if not exists products_tags_gin on products using gin (tags);
create index if not exists products_active on products (is_active) where is_active;

-- Categories: row/column headers in the grid
create table if not exists categories (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,             -- shown to players, e.g. "Made by Apple"
  description  text,                              -- optional admin note
  -- A category matches a product when ANY of these conditions match.
  -- JSON shape: { "tags": ["apple"], "manufacturer": ["Apple"], "kind": "hardware",
  --               "year_min": 2020, "year_max": 2024 }
  rule         jsonb not null default '{}'::jsonb,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

-- Pre-computed product/category satisfaction (refreshed when products or categories change)
create table if not exists product_categories (
  product_id  uuid not null references products(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  primary key (product_id, category_id)
);
create index if not exists pc_category_idx on product_categories (category_id);

-- Daily puzzles
create table if not exists puzzles (
  id           uuid primary key default gen_random_uuid(),
  puzzle_date  date not null unique,             -- one puzzle per day (ET)
  row_categories  uuid[] not null,                -- length 3
  col_categories  uuid[] not null,                -- length 3
  status       text not null default 'published' check (status in ('draft','published')),
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Anonymous players (UUID stored in localStorage)
create table if not exists players (
  id              uuid primary key,                -- generated client-side
  display_name    text,                            -- optional, used on leaderboard
  current_streak  int not null default 0,
  max_streak      int not null default 0,
  games_played    int not null default 0,
  perfect_games   int not null default 0,          -- 9/9
  total_correct   int not null default 0,
  last_played     date,
  created_at      timestamptz not null default now()
);

-- One row per cell-guess. Used for rarity stats and replay.
create table if not exists guesses (
  id           bigint generated by default as identity primary key,
  puzzle_id    uuid not null references puzzles(id) on delete cascade,
  player_id    uuid not null references players(id) on delete cascade,
  row_idx      int not null check (row_idx between 0 and 2),
  col_idx      int not null check (col_idx between 0 and 2),
  product_id   uuid references products(id),       -- null for incorrect / skipped
  raw_text     text,                                -- what they typed
  is_correct   boolean not null,
  created_at   timestamptz not null default now()
);

create unique index if not exists guesses_one_per_cell
  on guesses (puzzle_id, player_id, row_idx, col_idx);
create index if not exists guesses_rarity_lookup
  on guesses (puzzle_id, row_idx, col_idx, product_id) where is_correct;

-- Per-puzzle final results (one row per player per puzzle)
create table if not exists game_results (
  puzzle_id     uuid not null references puzzles(id) on delete cascade,
  player_id     uuid not null references players(id) on delete cascade,
  correct_count int not null,
  rarity_score  int not null,                      -- 0..900 (sum of 0..100 per cell)
  completed_at  timestamptz not null default now(),
  primary key (puzzle_id, player_id)
);
create index if not exists results_leaderboard
  on game_results (puzzle_id, rarity_score desc, correct_count desc);

-- =====================================================================
-- Row level security
-- =====================================================================
alter table products            enable row level security;
alter table categories          enable row level security;
alter table product_categories  enable row level security;
alter table puzzles             enable row level security;
alter table players             enable row level security;
alter table guesses             enable row level security;
alter table game_results        enable row level security;

-- Public read for active products + active categories + published puzzles
drop policy if exists "products_read" on products;
create policy "products_read" on products
  for select using (is_active);

drop policy if exists "categories_read" on categories;
create policy "categories_read" on categories
  for select using (is_active);

drop policy if exists "pc_read" on product_categories;
create policy "pc_read" on product_categories
  for select using (true);

drop policy if exists "puzzles_read" on puzzles;
create policy "puzzles_read" on puzzles
  for select using (status = 'published' and puzzle_date <= (now() at time zone 'America/New_York')::date);

-- Players: anyone can insert/update their own row (id is client-supplied UUID).
-- We trust the anon UUID — same model as NYT-style daily games.
drop policy if exists "players_read" on players;
create policy "players_read" on players for select using (true);
drop policy if exists "players_write" on players;
create policy "players_write" on players for insert with check (true);
drop policy if exists "players_update" on players;
create policy "players_update" on players for update using (true) with check (true);

-- Guesses + results: insert only, public read for aggregation
drop policy if exists "guesses_read" on guesses;
create policy "guesses_read" on guesses for select using (true);
drop policy if exists "guesses_write" on guesses;
create policy "guesses_write" on guesses for insert with check (true);

drop policy if exists "results_read" on game_results;
create policy "results_read" on game_results for select using (true);
drop policy if exists "results_write" on game_results;
create policy "results_write" on game_results for insert with check (true);
drop policy if exists "results_update" on game_results;
create policy "results_update" on game_results for update using (true) with check (true);

-- Admin operations (insert/update/delete on products, categories, puzzles)
-- are performed only by the service_role key, which bypasses RLS automatically.
-- The admin dashboard authenticates with the service_role key behind a password gate.
