-- =====================================================================
-- Seed data: ~140 products and ~30 categories.
-- Tags drive category matching. See 03_functions.sql for refresh logic.
-- =====================================================================

-- ---------- Products ------------------------------------------------
insert into products (name, slug, manufacturer, kind, release_year, tags, aliases) values
-- Apple hardware
('iPhone 15 Pro',       'iphone-15-pro',     'Apple',     'hardware', 2023, '{apple,smartphone,ios,mobile,has-camera,has-touchscreen,premium}', '{}'),
('iPhone SE (3rd gen)', 'iphone-se-3',       'Apple',     'hardware', 2022, '{apple,smartphone,ios,mobile,has-camera,has-touchscreen,budget}', '{iphone se}'),
('iPad Pro M4',         'ipad-pro-m4',       'Apple',     'hardware', 2024, '{apple,tablet,ipados,has-touchscreen,has-camera,premium}', '{ipad pro}'),
('MacBook Pro M3',      'macbook-pro-m3',    'Apple',     'hardware', 2023, '{apple,laptop,macos,arm,premium}', '{mbp}'),
('MacBook Air M2',      'macbook-air-m2',    'Apple',     'hardware', 2022, '{apple,laptop,macos,arm}', '{}'),
('Mac mini M2',         'mac-mini-m2',       'Apple',     'hardware', 2023, '{apple,desktop,macos,arm}', '{}'),
('Apple Watch Series 9','apple-watch-9',     'Apple',     'hardware', 2023, '{apple,wearable,watchos,has-touchscreen,has-camera-no}', '{}'),
('AirPods Pro 2',       'airpods-pro-2',     'Apple',     'hardware', 2022, '{apple,audio,wireless,earbuds}', '{airpods pro}'),
('Vision Pro',          'vision-pro',        'Apple',     'hardware', 2024, '{apple,vr,xr,wearable,premium,visionos}', '{apple vision pro}'),
-- Samsung / Google / OnePlus
('Galaxy S24 Ultra',    'galaxy-s24-ultra',  'Samsung',   'hardware', 2024, '{samsung,smartphone,android,mobile,has-camera,has-touchscreen,premium,has-stylus}', '{s24 ultra}'),
('Galaxy Z Fold 5',     'galaxy-z-fold-5',   'Samsung',   'hardware', 2023, '{samsung,smartphone,android,mobile,has-camera,has-touchscreen,foldable,premium}', '{z fold 5}'),
('Galaxy Tab S9',       'galaxy-tab-s9',     'Samsung',   'hardware', 2023, '{samsung,tablet,android,has-touchscreen,has-stylus}', '{}'),
('Pixel 8 Pro',         'pixel-8-pro',       'Google',    'hardware', 2023, '{google,smartphone,android,mobile,has-camera,has-touchscreen,premium,ai}', '{}'),
('Pixel Watch 2',       'pixel-watch-2',     'Google',    'hardware', 2023, '{google,wearable,wearos,has-touchscreen}', '{}'),
('Pixel Buds Pro',      'pixel-buds-pro',    'Google',    'hardware', 2022, '{google,audio,wireless,earbuds}', '{}'),
('Chromecast with Google TV', 'chromecast-google-tv', 'Google', 'hardware', 2020, '{google,streaming,tv,home}', '{chromecast}'),
('Nest Hub (2nd gen)',  'nest-hub-2',        'Google',    'hardware', 2021, '{google,smart-home,has-touchscreen,home}', '{nest hub}'),
('OnePlus 12',          'oneplus-12',        'OnePlus',   'hardware', 2024, '{oneplus,smartphone,android,mobile,has-camera,has-touchscreen,premium}', '{}'),
-- Microsoft / Xbox
('Xbox Series X',       'xbox-series-x',     'Microsoft', 'hardware', 2020, '{microsoft,xbox,console,gaming}', '{xsx}'),
('Xbox Series S',       'xbox-series-s',     'Microsoft', 'hardware', 2020, '{microsoft,xbox,console,gaming,budget}', '{xss}'),
('Surface Pro 10',      'surface-pro-10',    'Microsoft', 'hardware', 2024, '{microsoft,tablet,laptop,windows,has-touchscreen,has-stylus,premium,ai}', '{}'),
('Surface Laptop 7',    'surface-laptop-7',  'Microsoft', 'hardware', 2024, '{microsoft,laptop,windows,arm,ai}', '{}'),
-- Sony / Nintendo
('PlayStation 5',       'playstation-5',     'Sony',      'hardware', 2020, '{sony,playstation,console,gaming}', '{ps5}'),
('PlayStation 5 Pro',   'playstation-5-pro', 'Sony',      'hardware', 2024, '{sony,playstation,console,gaming,premium}', '{ps5 pro}'),
('DualSense Edge',      'dualsense-edge',    'Sony',      'hardware', 2023, '{sony,playstation,gaming,controller,accessory,premium}', '{}'),
('PSVR 2',              'psvr-2',            'Sony',      'hardware', 2023, '{sony,vr,xr,wearable,gaming}', '{}'),
('WH-1000XM5',          'wh-1000xm5',        'Sony',      'hardware', 2022, '{sony,audio,wireless,headphones,premium}', '{}'),
('Nintendo Switch OLED','nintendo-switch-oled','Nintendo','hardware', 2021, '{nintendo,console,gaming,handheld,has-touchscreen}', '{switch oled}'),
('Nintendo Switch Lite','nintendo-switch-lite','Nintendo','hardware', 2019, '{nintendo,console,gaming,handheld,has-touchscreen,budget}', '{switch lite}'),
-- Steam / Valve / Asus / Lenovo / Razer
('Steam Deck OLED',     'steam-deck-oled',   'Valve',     'hardware', 2023, '{valve,console,gaming,handheld,has-touchscreen,linux,steam}', '{steam deck}'),
('ROG Ally X',          'rog-ally-x',        'Asus',      'hardware', 2024, '{asus,console,gaming,handheld,has-touchscreen,windows}', '{ally x}'),
('Legion Go',           'legion-go',         'Lenovo',    'hardware', 2023, '{lenovo,console,gaming,handheld,has-touchscreen,windows}', '{}'),
('Razer Blade 16',      'razer-blade-16',    'Razer',     'hardware', 2024, '{razer,laptop,gaming,windows,premium}', '{}'),
('ThinkPad X1 Carbon',  'thinkpad-x1-carbon','Lenovo',    'hardware', 2024, '{lenovo,laptop,windows,business,premium}', '{}'),
-- Meta / VR / Wearables
('Meta Quest 3',        'meta-quest-3',      'Meta',      'hardware', 2023, '{meta,vr,xr,wearable,gaming}', '{quest 3}'),
('Meta Quest 3S',       'meta-quest-3s',     'Meta',      'hardware', 2024, '{meta,vr,xr,wearable,gaming,budget}', '{quest 3s}'),
('Ray-Ban Meta Smart Glasses','rayban-meta', 'Meta',      'hardware', 2023, '{meta,wearable,xr,has-camera,ai}', '{ray-ban meta}'),
-- Cameras / Drones / Audio
('GoPro Hero 12',       'gopro-hero-12',     'GoPro',     'hardware', 2023, '{gopro,camera,has-camera,action-cam}', '{}'),
('Sony A7 IV',          'sony-a7-iv',        'Sony',      'hardware', 2021, '{sony,camera,has-camera,mirrorless,premium}', '{a7 iv}'),
('DJI Mavic 3 Pro',     'dji-mavic-3-pro',   'DJI',       'hardware', 2023, '{dji,drone,has-camera,premium}', '{}'),
('DJI Osmo Pocket 3',   'dji-osmo-pocket-3', 'DJI',       'hardware', 2023, '{dji,camera,has-camera,handheld}', '{}'),
('Bose QuietComfort Ultra','bose-qc-ultra',  'Bose',      'hardware', 2023, '{bose,audio,wireless,headphones,premium}', '{}'),
('Sonos Era 300',       'sonos-era-300',     'Sonos',     'hardware', 2023, '{sonos,audio,smart-home,home}', '{}'),
-- E-readers / Misc
('Kindle Paperwhite',   'kindle-paperwhite', 'Amazon',    'hardware', 2021, '{amazon,e-reader,has-touchscreen}', '{}'),
('Kindle Scribe',       'kindle-scribe',     'Amazon',    'hardware', 2022, '{amazon,e-reader,has-touchscreen,has-stylus}', '{}'),
('Echo Show 10',        'echo-show-10',      'Amazon',    'hardware', 2021, '{amazon,smart-home,home,has-touchscreen}', '{}'),
('Fire TV Stick 4K Max','fire-tv-stick-4k-max','Amazon',  'hardware', 2023, '{amazon,streaming,tv,home}', '{}'),
('Roku Ultra',          'roku-ultra',        'Roku',      'hardware', 2024, '{roku,streaming,tv,home}', '{}'),
('Framework Laptop 16', 'framework-16',      'Framework', 'hardware', 2023, '{framework,laptop,modular,linux,windows}', '{}'),
('System76 Lemur Pro',  'lemur-pro',         'System76',  'hardware', 2023, '{system76,laptop,linux}', '{}'),

-- ---------- Software products --------------------------------------
('iOS 17',              'ios-17',            'Apple',     'software', 2023, '{apple,os,mobile,ios}', '{}'),
('iPadOS 17',           'ipados-17',         'Apple',     'software', 2023, '{apple,os,tablet,ipados}', '{}'),
('macOS Sonoma',        'macos-sonoma',      'Apple',     'software', 2023, '{apple,os,desktop,macos}', '{}'),
('watchOS 10',          'watchos-10',        'Apple',     'software', 2023, '{apple,os,wearable,watchos}', '{}'),
('Android 14',          'android-14',        'Google',    'software', 2023, '{google,os,mobile,android,open-source}', '{}'),
('ChromeOS',            'chromeos',          'Google',    'software', 2009, '{google,os,desktop,linux}', '{}'),
('Windows 11',          'windows-11',        'Microsoft', 'software', 2021, '{microsoft,os,desktop,windows}', '{}'),
('Ubuntu',              'ubuntu',            'Canonical', 'software', 2004, '{linux,os,desktop,open-source,canonical}', '{}'),
('Fedora',              'fedora',            'Red Hat',   'software', 2003, '{linux,os,desktop,open-source,redhat}', '{}'),
('Steam',               'steam',             'Valve',     'software', 2003, '{valve,gaming,desktop-app,launcher}', '{}'),
('Epic Games Store',    'epic-games-store',  'Epic Games','software', 2018, '{epic,gaming,desktop-app,launcher}', '{}'),
('Discord',             'discord',           'Discord',   'software', 2015, '{communication,chat,desktop-app,mobile-app,web-app,gaming}', '{}'),
('Slack',               'slack',             'Salesforce','software', 2013, '{communication,chat,desktop-app,mobile-app,web-app,productivity,enterprise}', '{}'),
('Microsoft Teams',     'microsoft-teams',   'Microsoft', 'software', 2017, '{microsoft,communication,chat,desktop-app,mobile-app,web-app,productivity,enterprise}', '{teams}'),
('Zoom',                'zoom',              'Zoom',      'software', 2013, '{communication,video,desktop-app,mobile-app,web-app,productivity}', '{}'),
('Google Meet',         'google-meet',       'Google',    'software', 2017, '{google,communication,video,web-app,mobile-app,productivity}', '{}'),
('Google Chrome',       'google-chrome',     'Google',    'software', 2008, '{google,browser,desktop-app,mobile-app}', '{chrome}'),
('Mozilla Firefox',     'firefox',           'Mozilla',   'software', 2002, '{mozilla,browser,desktop-app,mobile-app,open-source}', '{}'),
('Safari',              'safari',            'Apple',     'software', 2003, '{apple,browser,desktop-app,mobile-app}', '{}'),
('Microsoft Edge',      'microsoft-edge',    'Microsoft', 'software', 2015, '{microsoft,browser,desktop-app,mobile-app}', '{edge}'),
('Arc Browser',         'arc-browser',       'The Browser Company','software', 2022, '{browser,desktop-app,mobile-app}', '{arc}'),
('Brave',               'brave',             'Brave Software','software', 2016, '{browser,desktop-app,mobile-app,open-source,privacy}', '{}'),
('Notion',              'notion',            'Notion Labs','software',2016, '{productivity,notes,web-app,desktop-app,mobile-app}', '{}'),
('Obsidian',            'obsidian',          'Obsidian',  'software', 2020, '{productivity,notes,desktop-app,mobile-app,markdown}', '{}'),
('Evernote',            'evernote',          'Bending Spoons','software',2008, '{productivity,notes,web-app,desktop-app,mobile-app}', '{}'),
('Microsoft Word',      'microsoft-word',    'Microsoft', 'software', 1983, '{microsoft,productivity,office,desktop-app,mobile-app,web-app,enterprise}', '{word}'),
('Microsoft Excel',     'microsoft-excel',   'Microsoft', 'software', 1985, '{microsoft,productivity,office,desktop-app,mobile-app,web-app,enterprise,spreadsheet}', '{excel}'),
('Google Docs',         'google-docs',       'Google',    'software', 2006, '{google,productivity,office,web-app,mobile-app}', '{}'),
('Google Sheets',       'google-sheets',     'Google',    'software', 2006, '{google,productivity,office,web-app,mobile-app,spreadsheet}', '{}'),
('Apple Pages',         'apple-pages',       'Apple',     'software', 2005, '{apple,productivity,office,desktop-app,mobile-app}', '{pages}'),
('Apple Numbers',       'apple-numbers',     'Apple',     'software', 2007, '{apple,productivity,office,desktop-app,mobile-app,spreadsheet}', '{numbers}'),
('Adobe Photoshop',     'adobe-photoshop',   'Adobe',     'software', 1990, '{adobe,creative,desktop-app,enterprise,image-editor}', '{photoshop}'),
('Adobe Lightroom',     'adobe-lightroom',   'Adobe',     'software', 2007, '{adobe,creative,desktop-app,mobile-app,image-editor}', '{lightroom}'),
('Adobe Premiere Pro',  'adobe-premiere',    'Adobe',     'software', 2003, '{adobe,creative,desktop-app,enterprise,video-editor}', '{premiere}'),
('Final Cut Pro',       'final-cut-pro',     'Apple',     'software', 2011, '{apple,creative,desktop-app,video-editor}', '{}'),
('DaVinci Resolve',     'davinci-resolve',   'Blackmagic Design','software',2003, '{creative,desktop-app,video-editor}', '{resolve}'),
('Figma',               'figma',             'Adobe',     'software', 2016, '{adobe,creative,web-app,desktop-app,design,collaboration}', '{}'),
('Sketch',              'sketch',            'Sketch B.V.','software', 2010, '{creative,desktop-app,design,macos}', '{}'),
('Canva',               'canva',             'Canva',     'software', 2013, '{creative,web-app,mobile-app,design}', '{}'),
('Spotify',             'spotify',           'Spotify',   'software', 2008, '{streaming,music,audio,web-app,mobile-app,desktop-app}', '{}'),
('Apple Music',         'apple-music',       'Apple',     'software', 2015, '{apple,streaming,music,audio,mobile-app,desktop-app}', '{}'),
('YouTube',             'youtube',           'Google',    'software', 2005, '{google,streaming,video,web-app,mobile-app}', '{}'),
('YouTube Music',       'youtube-music',     'Google',    'software', 2015, '{google,streaming,music,audio,mobile-app,web-app}', '{}'),
('Netflix',             'netflix',           'Netflix',   'software', 2007, '{streaming,video,mobile-app,web-app,tv-app}', '{}'),
('Disney+',             'disney-plus',       'Disney',    'software', 2019, '{streaming,video,mobile-app,web-app,tv-app}', '{disney+}'),
('Hulu',                'hulu',              'Disney',    'software', 2008, '{streaming,video,mobile-app,web-app,tv-app}', '{}'),
('Max',                 'max',               'Warner Bros. Discovery','software',2020, '{streaming,video,mobile-app,web-app,tv-app}', '{hbo max}'),
('Prime Video',         'prime-video',       'Amazon',    'software', 2006, '{amazon,streaming,video,mobile-app,web-app,tv-app}', '{amazon prime video}'),
('Twitch',              'twitch',            'Amazon',    'software', 2011, '{amazon,streaming,video,mobile-app,web-app,gaming}', '{}'),
('TikTok',              'tiktok',            'ByteDance', 'software', 2018, '{social,video,mobile-app,web-app}', '{}'),
('Instagram',           'instagram',         'Meta',      'software', 2010, '{meta,social,mobile-app,web-app}', '{}'),
('Facebook',            'facebook',          'Meta',      'software', 2004, '{meta,social,mobile-app,web-app}', '{}'),
('WhatsApp',            'whatsapp',          'Meta',      'software', 2009, '{meta,communication,chat,mobile-app,desktop-app,web-app}', '{}'),
('Threads',             'threads',           'Meta',      'software', 2023, '{meta,social,mobile-app,web-app}', '{}'),
('X',                   'x-twitter',         'X Corp',    'software', 2006, '{social,mobile-app,web-app}', '{twitter}'),
('Reddit',              'reddit',            'Reddit',    'software', 2005, '{social,mobile-app,web-app,community}', '{}'),
('LinkedIn',            'linkedin',          'Microsoft', 'software', 2003, '{microsoft,social,mobile-app,web-app,enterprise}', '{}'),
('Mastodon',            'mastodon',          'Mastodon',  'software', 2016, '{social,mobile-app,web-app,open-source,decentralized}', '{}'),
('Bluesky',             'bluesky',           'Bluesky',   'software', 2023, '{social,mobile-app,web-app,decentralized}', '{}'),
('Signal',              'signal',            'Signal Foundation','software',2014, '{communication,chat,mobile-app,desktop-app,open-source,privacy}', '{}'),
('Telegram',            'telegram',          'Telegram',  'software', 2013, '{communication,chat,mobile-app,desktop-app,web-app}', '{}'),
('Visual Studio Code',  'vscode',            'Microsoft', 'software', 2015, '{microsoft,developer,desktop-app,open-source}', '{vs code,vscode}'),
('JetBrains IntelliJ IDEA','intellij',       'JetBrains', 'software', 2001, '{jetbrains,developer,desktop-app,enterprise}', '{intellij}'),
('Xcode',               'xcode',             'Apple',     'software', 2003, '{apple,developer,desktop-app,macos}', '{}'),
('Android Studio',      'android-studio',    'Google',    'software', 2013, '{google,developer,desktop-app}', '{}'),
('Sublime Text',        'sublime-text',      'Sublime HQ','software', 2008, '{developer,desktop-app}', '{}'),
('Vim',                 'vim',               'Bram Moolenaar','software',1991, '{developer,desktop-app,open-source,terminal}', '{}'),
('GitHub',              'github',            'Microsoft', 'software', 2008, '{microsoft,developer,web-app,enterprise}', '{}'),
('GitLab',              'gitlab',            'GitLab',    'software', 2014, '{developer,web-app,enterprise,open-source}', '{}'),
('Docker Desktop',      'docker-desktop',    'Docker',    'software', 2016, '{developer,desktop-app,enterprise}', '{}'),
('ChatGPT',             'chatgpt',           'OpenAI',    'software', 2022, '{ai,openai,web-app,mobile-app,desktop-app}', '{}'),
('Claude',              'claude',            'Anthropic', 'software', 2023, '{ai,anthropic,web-app,mobile-app,desktop-app}', '{}'),
('Gemini',              'gemini',            'Google',    'software', 2023, '{google,ai,web-app,mobile-app}', '{bard}'),
('Microsoft Copilot',   'microsoft-copilot', 'Microsoft', 'software', 2023, '{microsoft,ai,web-app,mobile-app,desktop-app}', '{copilot}'),
('Perplexity',          'perplexity',        'Perplexity AI','software',2022, '{ai,web-app,mobile-app}', '{}'),
('Midjourney',          'midjourney',        'Midjourney','software', 2022, '{ai,creative,image-editor,discord-bot}', '{}'),
('GitHub Copilot',      'github-copilot',    'Microsoft', 'software', 2021, '{microsoft,ai,developer}', '{}'),
('Notion AI',           'notion-ai',         'Notion Labs','software',2023, '{ai,productivity,web-app,desktop-app,mobile-app}', '{}'),
('1Password',           'onepassword',       'AgileBits', 'software', 2006, '{productivity,security,desktop-app,mobile-app,web-app,privacy}', '{}'),
('Bitwarden',           'bitwarden',         'Bitwarden', 'software', 2016, '{productivity,security,desktop-app,mobile-app,web-app,open-source,privacy}', '{}'),
('Last Pass',           'lastpass',          'LastPass',  'software', 2008, '{productivity,security,desktop-app,mobile-app,web-app}', '{lastpass}'),
('Dropbox',             'dropbox',           'Dropbox',   'software', 2008, '{productivity,storage,cloud,desktop-app,mobile-app,web-app}', '{}'),
('Google Drive',        'google-drive',      'Google',    'software', 2012, '{google,productivity,storage,cloud,desktop-app,mobile-app,web-app}', '{}'),
('iCloud Drive',        'icloud-drive',      'Apple',     'software', 2011, '{apple,productivity,storage,cloud,desktop-app,mobile-app,web-app}', '{icloud}'),
('OneDrive',            'onedrive',          'Microsoft', 'software', 2007, '{microsoft,productivity,storage,cloud,desktop-app,mobile-app,web-app}', '{}')
on conflict (slug) do nothing;

-- ---------- Categories ----------------------------------------------
-- The 'rule' jsonb defines what counts as a match. Refresh function
-- (see 03_functions.sql) populates product_categories accordingly.
insert into categories (name, description, rule) values
('Made by Apple',         'Manufacturer = Apple',                     '{"manufacturer":["Apple"]}'),
('Made by Google',         'Manufacturer = Google',                   '{"manufacturer":["Google"]}'),
('Made by Microsoft',      'Manufacturer = Microsoft',                '{"manufacturer":["Microsoft"]}'),
('Made by Samsung',        'Manufacturer = Samsung',                  '{"manufacturer":["Samsung"]}'),
('Made by Sony',           'Manufacturer = Sony',                     '{"manufacturer":["Sony"]}'),
('Made by Meta',           'Manufacturer = Meta',                     '{"manufacturer":["Meta"]}'),
('Made by Amazon',         'Manufacturer = Amazon',                   '{"manufacturer":["Amazon"]}'),
('Made by Adobe',          'Manufacturer = Adobe',                    '{"manufacturer":["Adobe"]}'),

('Hardware',               'kind = hardware',                         '{"kind":"hardware"}'),
('Software / App',         'kind = software',                         '{"kind":"software"}'),

('Released 2020 or later', 'release_year >= 2020',                    '{"year_min":2020}'),
('Released before 2015',   'release_year < 2015',                     '{"year_max":2014}'),
('Released in 2023',       'release_year = 2023',                     '{"year_min":2023,"year_max":2023}'),
('Released in 2024',       'release_year = 2024',                     '{"year_min":2024,"year_max":2024}'),

('Smartphone',             'has tag smartphone',                      '{"tags":["smartphone"]}'),
('Laptop',                 'has tag laptop',                          '{"tags":["laptop"]}'),
('Tablet',                 'has tag tablet',                          '{"tags":["tablet"]}'),
('Wearable',               'has tag wearable',                        '{"tags":["wearable"]}'),
('Gaming Console',         'has tag console',                         '{"tags":["console"]}'),
('Handheld',               'has tag handheld',                        '{"tags":["handheld"]}'),
('VR/XR',                  'has tag vr or xr',                        '{"tags":["vr","xr"]}'),
('Has a Camera',           'has tag has-camera',                      '{"tags":["has-camera"]}'),
('Has a Touchscreen',      'has tag has-touchscreen',                 '{"tags":["has-touchscreen"]}'),
('Has a Stylus',           'has tag has-stylus',                      '{"tags":["has-stylus"]}'),

('Mobile App',             'has tag mobile-app or mobile',            '{"tags":["mobile-app","mobile"]}'),
('Web App',                'has tag web-app',                         '{"tags":["web-app"]}'),
('Desktop App',            'has tag desktop-app',                     '{"tags":["desktop-app"]}'),
('Open Source',            'has tag open-source',                     '{"tags":["open-source"]}'),
('AI / LLM Product',       'has tag ai',                              '{"tags":["ai"]}'),
('Streaming Service',      'has tag streaming',                       '{"tags":["streaming"]}'),
('Productivity Tool',      'has tag productivity',                    '{"tags":["productivity"]}'),
('Communication / Chat',   'has tag communication',                   '{"tags":["communication"]}'),
('Browser',                'has tag browser',                         '{"tags":["browser"]}'),
('Developer Tool',         'has tag developer',                       '{"tags":["developer"]}'),
('Audio Hardware',         'has tag audio',                           '{"tags":["audio"]}'),
('Camera / Imaging',       'has tag camera',                          '{"tags":["camera"]}'),
('Smart Home',             'has tag smart-home',                      '{"tags":["smart-home"]}'),
('Runs on Android',        'has tag android',                         '{"tags":["android"]}'),
('Runs on iOS / iPadOS',   'has tag ios or ipados',                   '{"tags":["ios","ipados"]}'),
('Runs on Windows',        'has tag windows',                         '{"tags":["windows"]}'),
('Runs on macOS',          'has tag macos',                           '{"tags":["macos"]}'),
('Runs on Linux',          'has tag linux',                           '{"tags":["linux"]}'),
('Gaming-related',         'has tag gaming',                          '{"tags":["gaming"]}'),
('Premium / Pro tier',     'has tag premium',                         '{"tags":["premium"]}'),
('Creative Tool',          'has tag creative',                        '{"tags":["creative"]}'),
('Social Network',         'has tag social',                          '{"tags":["social"]}'),
('Cloud Storage',          'has tag cloud or storage',                '{"tags":["cloud","storage"]}')
on conflict (name) do nothing;
