-- =====================================================================
-- Feedback collection.
--
-- Players submit feedback from the embedded game; rows land here, the
-- admin "Feedback" tab reads them. Email forwarding to rich.w@valnetinc.com
-- is intentionally NOT done in-database — see notes at the bottom for the
-- recommended setup (Supabase Database Webhook → Zapier or similar) which
-- can be enabled without changing this schema.
-- =====================================================================

create table if not exists feedback (
  id           bigint generated by default as identity primary key,
  player_id    uuid references players(id) on delete set null,
  display_name text,
  contact      text,                                  -- optional email/handle the player provides
  message      text not null,
  status       text not null default 'new'
                 check (status in ('new','read','archived')),
  user_agent   text,
  page_url     text,                                  -- where the form was submitted from
  created_at   timestamptz not null default now()
);

create index if not exists feedback_status_created
  on feedback (status, created_at desc);

alter table feedback enable row level security;

-- Anonymous players can INSERT feedback (the RPC is the actual gate; a stray
-- direct POST would also work, but RLS keeps reads locked down).
drop policy if exists "feedback_insert" on feedback;
create policy "feedback_insert" on feedback for insert with check (true);

-- No SELECT policy → anon role cannot read; only service_role (admin) can.

-- ---------- submit_feedback RPC ------------------------------------
create or replace function submit_feedback(
  p_player_id    uuid,
  p_display_name text,
  p_contact      text,
  p_message      text,
  p_user_agent   text default null,
  p_page_url     text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  msg  text := trim(coalesce(p_message, ''));
  name text := nullif(trim(coalesce(p_display_name, '')), '');
  ctc  text := nullif(trim(coalesce(p_contact, '')), '');
begin
  if length(msg) < 5 then
    return jsonb_build_object('ok', false, 'reason', 'too_short');
  end if;
  if length(msg) > 4000 then
    return jsonb_build_object('ok', false, 'reason', 'too_long');
  end if;
  -- Soft rate-limit: same player can't spam more than 5 in last hour.
  if p_player_id is not null and (
    select count(*) from feedback
     where player_id = p_player_id
       and created_at > now() - interval '1 hour'
  ) >= 5 then
    return jsonb_build_object('ok', false, 'reason', 'rate_limited');
  end if;

  insert into feedback (player_id, display_name, contact, message, user_agent, page_url)
  values (p_player_id, name, ctc, msg,
          left(coalesce(p_user_agent, ''), 500),
          left(coalesce(p_page_url, ''), 500));
  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function submit_feedback(uuid, text, text, text, text, text) to anon, authenticated;

-- =====================================================================
-- Email forwarding notes (do this AFTER tables exist):
--
-- Easiest path: Supabase Dashboard → Database → Webhooks → "Insert: feedback"
-- triggering a webhook to a Zapier/Pipedream/n8n workflow that emails
-- rich.w@valnetinc.com with subject "Tech Grid Feedback".
--
-- Zapier "Webhooks by Zapier → Catch Hook" + "Email by Zapier → Send Outbound
-- Email" is the simplest path; works on the free tier.
-- =====================================================================
